name: BetterCallFishing
version: '${version}'
main: xyz.sherhsnyaga.bettercallfishing.BetterCallFishing
api-version: '1.16'
load: STARTUP
authors: [ Shershnyaga_ ]
website: shershnyaga.xyz
commands:
  bettercallfishing:
    permission: bettercallfishing.*
permissions:
  bettercallfishing.*:
    default: op