on: 
    push:
    workflow_call:
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle
      - name: Build with Gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: ${{ github.workflow	}}-"default"
          arguments: "build"
          gradle-version: "wrapper"
          build-root-directory: "."
          read-only: false
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BetterCallFishing
          path: "build/libs/*.jar"